import Layout from "../components/layout/Layout";
import "../styles/globals.css";

// Components

// Header medata
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  // const route = children.props.childProp.segment;

  return (
    <html lang="bg">
      <body className="h-screen min-h-screen">
          <Layout>{children}</Layout>
      </body>
    </html>
  );
}
