import "../styles/globals.css";

import Layout from "../components/layout/Layout";
import Script from "next/script";
import ToastContainer from "../components/layout/ToastContainer"

// Components

// Header medata
// export const metadata = {
//   // title: "Next.js",
//   // description: "Generated by Next.js",
//   // viewport: 
// };
export default function RootLayout({ children }) {
  // const route = children.props.childProp.segment;

  return (
    <html lang="bg" className="">
      <head>
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
      />
      <Script strategy="afterInteractive" id="my-script">
        {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
    page_path: window.location.pathname,
    });
`}
      </Script>
        <link rel="icon" href="/logos/web-spider.svg" />
       
        <meta
          property="og:title"
          content="Strover Company | Продавайте и печелете повече онлайн | Експерти в онлайн търговията | SEO | Google Ads | Дигитален маркетинг"
        />
        <meta
          property="og:description"
          content="Strover Company изработва, поддържа и развива сайтове. Предлага услуги в сферата на дигиталният маркетинг, като включва SEO, създаване, поддържане и развиване на социални мрежи, брандиране и ребрандиране. За всичко което Ви трябва да е на едно място, на достъпна цена с прекрасно обслужване."
        />
        <meta
          property="og:image"
          content="https://www.linkpicture.com/q/STROVER-POST.jpg"
        />
        <meta property="og:url" content="https://strover.bg/" />
        <meta name="robots" content="index, follow" />

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="canonical" href="https://strover.bg/" />
      </head>
      <body className="">
          <Layout>{children}</Layout>
          <ToastContainer/>
      </body> 
    </html>
  );
}
