// Next things
import Head from "next/head";
import Image from "next/legacy/image";
import Brands from "../components/Brands";

// Components
import AboutUs from "../components/indexPage/AboutUs";
import FirmsWhoTrust from "../components/indexPage/FirmsWhoTrust";
import HeroSection from "../components/indexPage/HeroSection";
import Navigation from "../components/indexPage/Navigation";
import Services from "../components/indexPage/Services";

// Icons

export default function Home() {
  return (
    <div className=" index-bg">
      <Head>
        <title>Strover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />

      <main className="mt-5 h-full">
        <HeroSection />
        <AboutUs />
        <Services />
        <FirmsWhoTrust />
        <Brands />
      </main>
    </div>
  );
}
